import type { LessonModule } from "./types";

export const RETURNS_MODULE: LessonModule = {
  id: "returns",
  title: "Returns",
  subtitle: "Why money grows — compounding, percentages, and inflation",
  level: "Foundations",
  estimatedMinutes: 8,
  unlocks: ["Compound Calculator widget in Portfolio", "+7 days AI credits"],
  blocks: [
    {
      id: "r1",
      kind: "concept",
      title: "Returns mean two things",
      body: "A return is what your money earns over time. It can be a percent (5%) or a dollar amount ($500). Both matter — but they tell different stories.",
      visual: "compounding",
      terms: ["return", "percent", "dollar amount"],
    },
    {
      id: "r2",
      kind: "interactive",
      title: "Play with compounding",
      prompt: "Drag the sliders. Notice how time changes the answer more than rate or contribution.",
      widget: { type: "compound", defaults: { monthly: 500, years: 20, rate: 7 } },
      tutor: "Let's see compounding in action. There are three sliders: monthly contribution, number of years, and annual return. Try doubling the monthly amount — the final value roughly doubles. Now reset and double the years instead. You'll notice the final value jumps far more than double. That gap between the green line and the flat amount you put in is compounding doing the work. The takeaway: time is the strongest lever you have.",
    },
    {
      id: "r3",
      kind: "insight",
      title: "Time is the heaviest lever",
      body: "Doubling your monthly amount roughly doubles your end value. Doubling your years more than doubles it — sometimes triples it. That's compounding.",
      terms: ["compounding"],
    },
    {
      id: "r4",
      kind: "concept",
      title: "Percent vs dollars",
      body: "A 10% return on $1,000 is $100. A 10% return on $1M is $100,000. Same percent, very different impact. As your portfolio grows, the dollar amount grows faster than the percent suggests.",
      terms: ["portfolio", "return"],
    },
    {
      id: "r5",
      kind: "interactive",
      title: "Inflation eats returns",
      prompt: "Move the inflation slider. The grey line is what your money is actually worth.",
      widget: { type: "real-vs-nominal", defaults: { years: 20, nominal: 7, inflation: 3 } },
      tutor: "Here's why inflation matters. The green line shows your money growing at the nominal return — the headline number. The grey line shows what that money is actually worth after inflation eats into it. Slide inflation up and watch the grey line flatten. Even a small gap, like seven percent return minus three percent inflation, leaves you with about four percent of real growth. That's the number you can actually spend.",
    },
    {
      id: "r6",
      kind: "insight",
      title: "Real return is what you live on",
      body: "Earning 7% with 3% inflation means you're really only growing at about 4%. Always think in real returns when planning long-term.",
      terms: ["inflation", "real returns", "real return"],
    },
    {
      id: "r7",
      kind: "checkpoint",
      concept: "Compounding, percent vs dollars, real vs nominal returns",
      question: "If you had to explain to a friend why starting to invest at 22 instead of 32 matters so much, what would you say?",
      keyIdeas: [
        "Time multiplies returns more than rate or contribution",
        "Compounding builds on itself each year",
        "An extra decade can roughly double the end value",
      ],
      placeholder: "Type a few sentences in your own words...",
    },
    {
      id: "r8",
      kind: "sim",
      title: "See the time lever in action",
      prompt: "Same $500/month, same 7% expected return. The only difference: how many years each investor stays invested. Drag the sliders to compare.",
      mode: "compounding",
      monthlyContribution: 500,
      expectedAnnualReturn: 0.07,
      portfolios: [
        { label: "Early starter (age 22 → 65)", preset: "early-start", years: 43 },
        { label: "Late starter (age 32 → 65)", preset: "late-start", years: 33 },
      ],
      durationYears: 43,
      startingValue: 0,
    },
    {
      id: "r9",
      kind: "reward",
      unlocks: ["Compound Calculator unlocked in Portfolio", "+7 days AI credits earned"],
    },
  ],
};
